INSERT INTO coagus_test(ITEMCODE, itemgroupcode, NAME, GROUPTYPE, PROJECTCODE, NEWMINCARDINALITY, NEWMAXCARDINALITY) VALUES ('CODE11','GROUPCODE11','NAME11','GROUPTYPE11','PROJECT11',11,11);
INSERT INTO coagus_test(ITEMCODE, itemgroupcode, NAME, GROUPTYPE, PROJECTCODE, NEWMINCARDINALITY, NEWMAXCARDINALITY) VALUES ('CODE12','GROUPCODE12','NAME12','GROUPTYPE12','PROJECT12',12,12);
INSERT INTO coagus_test(ITEMCODE, itemgroupcode, NAME, GROUPTYPE, PROJECTCODE, NEWMINCARDINALITY, NEWMAXCARDINALITY) VALUES ('CODE13','GROUPCODE13','NAME13','GROUPTYPE13','PROJECT13',13,13);
INSERT INTO coagus_test(ITEMCODE, itemgroupcode, NAME, GROUPTYPE, PROJECTCODE, NEWMINCARDINALITY, NEWMAXCARDINALITY) VALUES ('CODE14','GROUPCODE14','NAME14','GROUPTYPE14','PROJECT14',14,14);
INSERT INTO coagus_test(ITEMCODE, itemgroupcode, NAME, GROUPTYPE, PROJECTCODE, NEWMINCARDINALITY, NEWMAXCARDINALITY) VALUES ('CODE15','GROUPCODE15','NAME15','GROUPTYPE15','PROJECT15',15,15);

commit;