UPDATE coagus_test SET ITEMGROUPCODE = 'GROUPCODE11' WHERE ITEMCODE = 'CODE1';
UPDATE coagus_test SET ITEMGROUPCODE = 'GROUPCODE22' WHERE ITEMCODE = 'CODE2';
UPDATE coagus_test SET ITEMGROUPCODE = 'GROUPCODE33' WHERE ITEMCODE = 'CODE2';

commit;